#!/bin/sh
set -e
mustbedir () { echo "Script must be run from inside of the cloned directory." && exit 1 }

[ "$(basename "$PWD")" = "zish" ] && ZISHDIR="$PWD" || mustbedir
if [ "$EUID" -e 0 ]; then
	read -p -r "Warning: changes made as root user only affect the root user. Continue? (y/n)" ROOTCONFIRM
	[ "$ROOTCONFIRM" = "n" ] && exit
fi

[ -f /bin/zsh ] || exit 1
[ -f "$HOME/.zshrc" ] && mv "$HOME/.zshrc" "$HOME/zshrc.old" && echo "~/.zshrc moved to ~/zshrc.old"

echo 'export ZDOTDIR=$HOME/.config/zsh' | sudo tee -a /etc/zsh/zshenv
mkdir -p "$HOME/.config/zsh/"
cp "$ZISHDIR/zshrc" "$HOME/.config/zsh/.zshrc"

[ -d /usr/share/zsh/plugins/ ] || sudo mkdir -p /usr/share/zsh/plugins/
cd /usr/share/zsh/plugins/

sudo git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
sudo git clone https://github.com/zsh-users/zsh-autosuggestions.git
sudo git clone https://github.com/zsh-users/zsh-history-substring-search.git
sudo git clone https://github.com/zsh-users/zsh-completions.git
cd -

echo "Done!"
